// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJafie7j2QRHUwUo6L4GFj2-u-BDEysdA',
    appId: '1:411919725527:web:7ab0a677e543b3239a1192',
    messagingSenderId: '411919725527',
    projectId: 'study-app-f0e3b',
    authDomain: 'study-app-f0e3b.firebaseapp.com',
    storageBucket: 'study-app-f0e3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcP35-B6JLlf-SMmvlY4tIDtuInPdv8SY',
    appId: '1:411919725527:android:dab41e363ccefc6f9a1192',
    messagingSenderId: '411919725527',
    projectId: 'study-app-f0e3b',
    storageBucket: 'study-app-f0e3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4afwzH_40blXOiaqLjuAEeHlDBWxn45I',
    appId: '1:411919725527:ios:a07e462264f9017e9a1192',
    messagingSenderId: '411919725527',
    projectId: 'study-app-f0e3b',
    storageBucket: 'study-app-f0e3b.appspot.com',
    iosClientId: '411919725527-tsgddl1dgear5aii3c6bhv0hcov74c0s.apps.googleusercontent.com',
    iosBundleId: 'com.codeconline.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4afwzH_40blXOiaqLjuAEeHlDBWxn45I',
    appId: '1:411919725527:ios:a07e462264f9017e9a1192',
    messagingSenderId: '411919725527',
    projectId: 'study-app-f0e3b',
    storageBucket: 'study-app-f0e3b.appspot.com',
    iosClientId: '411919725527-tsgddl1dgear5aii3c6bhv0hcov74c0s.apps.googleusercontent.com',
    iosBundleId: 'com.codeconline.flutterStudyApp',
  );
}
